import { app, BrowserWindow, Menu, MenuItem, IpcMainEvent, Event, Input, WebContents } from 'electron'
import { ipcMain as ipc } from 'electron'
import { dialog } from 'electron'
import { clipboard } from 'electron'
import fs from 'fs'
import path from 'path'
import Store, { Schema } from 'electron-store'
import { convertStateToPlantUML, convertPlantUMLToState } from './conversion/uml'
import { convertStateToYAML } from './conversion/yaml'
import { convertStateToJSON } from './conversion/json'
import { convertTextToMindMap } from './conversion/text-to-mindmap'
import { completeState } from './completion'
import { migrateState1to2 } from './conversion/migrate'
import { SavingNodeState } from './types'

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string

declare const SETTINGS_WEBPACK_ENTRY: string
declare const SETTINGS_PRELOAD_WEBPACK_ENTRY: string

const CONFIRM_ANSWER_SAVE = 0
const CONFIRM_ANSWER_DELETE = 1
const CONFIRM_ANSWER_CANCEL = 2

const DEFAULT_TITLE = 'Unnamed'
const DATA_VERSION = 2

interface DocumentState {
  filePath: string | null
  editDirty: boolean
  rootText: string | null
  exportFilePath: string | null
  onSavedFunction: (() => void) | null
  completionAbortController: AbortController | null
}

const documentStates = new Map<number, DocumentState>()

// アプリ起動前にopen-fileイベントで渡されたファイルパスを保持
let pendingFilePath: string | null = null

// ウィンドウ間コピペ用の共有バッファ
let sharedCopiedNodes: SavingNodeState[] | null = null

const createInitialDocState = (): DocumentState => ({
  filePath: null,
  editDirty: false,
  rootText: null,
  exportFilePath: null,
  onSavedFunction: null,
  completionAbortController: null
})

const isDocumentWindow = (win: BrowserWindow): boolean => {
  return documentStates.has(win.id)
}

const getDocState = (win: BrowserWindow): DocumentState => {
  const state = documentStates.get(win.id)
  if (state == null) {
    throw new Error(`Document state not found for window ${win.id}`)
  }
  return state
}

const getDocWindowFromSender = (sender: WebContents): BrowserWindow | null => {
  const win = BrowserWindow.fromWebContents(sender)
  if (win == null || !isDocumentWindow(win)) {
    return null
  }
  return win
}

const getDocumentWindows = (): BrowserWindow[] => {
  return BrowserWindow.getAllWindows().filter(isDocumentWindow)
}

const getWindowTitle = (docState: DocumentState): string => {
  if (docState.filePath != null) {
    const name = path.basename(docState.filePath)
    return docState.editDirty ? `*${name}` : name
  }
  return docState.editDirty ? `*${DEFAULT_TITLE}` : DEFAULT_TITLE
}

const updateWindowTitle = (win: BrowserWindow, docState: DocumentState): void => {
  win.setTitle(getWindowTitle(docState))
}

const findDocumentWindowByPath = (filePath: string): BrowserWindow | null => {
  for (const win of getDocumentWindows()) {
    const docState = getDocState(win)
    if (docState.filePath === filePath) {
      return win
    }
  }
  return null
}

const focusDocumentWindow = (win: BrowserWindow): void => {
  if (win.isMinimized()) {
    win.restore()
  }
  win.show()
  win.focus()
}

const getFocusedDocumentWindow = (): BrowserWindow | null => {
  const focused = BrowserWindow.getFocusedWindow()
  if (focused != null && isDocumentWindow(focused)) {
    return focused
  }
  const docs = getDocumentWindows()
  return docs.length > 0 ? docs[docs.length - 1] : null
}

const resolveDocumentWindow = (browserWindow: BrowserWindow | undefined): BrowserWindow => {
  if (browserWindow != null && isDocumentWindow(browserWindow)) {
    return browserWindow
  }
  const focused = getFocusedDocumentWindow()
  if (focused != null) {
    return focused
  }
  return createDocumentWindow()
}

const cancelCompletionForWindow = (win: BrowserWindow): void => {
  const docState = getDocState(win)
  if (docState.completionAbortController != null) {
    docState.completionAbortController.abort()
    docState.completionAbortController = null
  }
}

interface StoreSchema {
  darkMode: boolean
  openaiApiKey: string
  completionModel: string
  completionContext: string
}

const schema: Schema<StoreSchema> = {
  darkMode: {
    type: 'boolean',
    default: false
  },
  openaiApiKey: {
    type: 'string',
    default: ''
  },
  completionModel: {
    type: 'string',
    default: 'gpt-5-mini'
  },
  completionContext: {
    type: 'string',
    default: ''
  }
}

const store = new Store({ schema })

const setDarkMode = (darkMode: boolean) => {
  getDocumentWindows().forEach((window) => {
    window.webContents.send('request', 'dark-mode', darkMode)
  })
}

const onDarkModeChanged = (newValue: boolean, oldValue: boolean) => {
  setDarkMode(newValue)
}

store.onDidChange('darkMode', onDarkModeChanged)

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit()
}

const showSaveConfirmDialog = () => {
  const ret = dialog.showMessageBoxSync({
    type: 'info',
    buttons: ['Save', 'Delete', 'Cancel'],
    message: 'File not saved. Save?'
  })

  return ret
}

const saveOptions = {
  title: 'Save',
  filters: [
    {
      name: 'Data',
      extensions: ['nm']
    }
  ]
}

const exportOptionsUML = {
  title: 'Export (PlantUML)',
  filters: [
    {
      name: 'Data',
      extensions: ['pu']
    }
  ]
}

const exportOptionsYAML = {
  title: 'Export (YAML)',
  filters: [
    {
      name: 'Data',
      extensions: ['yaml', 'yml']
    }
  ]
}

const exportOptionsJSON = {
  title: 'Export (JSON)',
  filters: [
    {
      name: 'Data',
      extensions: ['json']
    }
  ]
}

const onSaveFinished = (browserWindow: BrowserWindow, docState: DocumentState) => {
  if (docState.filePath != null) {
    app.addRecentDocument(docState.filePath)
  }
  updateWindowTitle(browserWindow, docState)

  if (docState.onSavedFunction != null) {
    const fn = docState.onSavedFunction
    docState.onSavedFunction = null
    fn()
  }
}

const save = (browserWindow: BrowserWindow, onSavedHook: (() => void) | null = null) => {
  const docState = getDocState(browserWindow)

  if (docState.filePath == null) {
    const saveOptions_ = Object.create(saveOptions)

    if (docState.rootText != null) {
      saveOptions_['defaultPath'] = docState.rootText
    }

    const path_ = dialog.showSaveDialogSync(saveOptions_)
    if (path_ != null) {
      docState.onSavedFunction = onSavedHook
      docState.filePath = path_
      updateWindowTitle(browserWindow, docState)
      browserWindow.webContents.send('request', 'save')
    }
  } else {
    docState.onSavedFunction = onSavedHook
    browserWindow.webContents.send('request', 'save')
  }
}

const saveAs = (browserWindow: BrowserWindow) => {
  const docState = getDocState(browserWindow)
  const saveOptions_ = Object.create(saveOptions)
  if (docState.rootText != null) {
    saveOptions_['defaultPath'] = docState.rootText
  }
  const path_ = dialog.showSaveDialogSync(saveOptions_)
  if (path_ != null) {
    docState.filePath = path_
    updateWindowTitle(browserWindow, docState)
    browserWindow.webContents.send('request', 'save')
  }
}

const exportAs = (browserWindow: BrowserWindow, format: 'uml' | 'yaml' | 'json') => {
  const docState = getDocState(browserWindow)
  const exportOptions_ = Object.create(
    format == 'uml' ? exportOptionsUML : format == 'json' ? exportOptionsJSON : exportOptionsYAML
  )

  if (docState.filePath != null) {
    const baseName = path.basename(docState.filePath, '.nm')
    exportOptions_['defaultPath'] = baseName
  } else {
    if (docState.rootText != null) {
      exportOptions_['defaultPath'] = docState.rootText
    }
  }

  const path_ = dialog.showSaveDialogSync(exportOptions_)

  if (path_ != null) {
    docState.exportFilePath = path_
    browserWindow.webContents.send('request', 'export', format)
  }
}

const load = (browserWindow: BrowserWindow, path_: string) => {
  fs.readFile(path_, (error: NodeJS.ErrnoException, buffer: Buffer) => {
    if (error != null) {
      console.log('file open error')
      return
    }

    if (buffer != null) {
      const json = buffer.toString('utf8')
      const mapData = JSON.parse(json)
      const version = mapData['version']
      let state = mapData['state']

      if (version == 1) {
        state = migrateState1to2(state)
      }

      browserWindow.webContents.send('request', 'load', state)

      const docState = getDocState(browserWindow)
      docState.editDirty = false
      docState.filePath = path_
      app.addRecentDocument(path_)
      updateWindowTitle(browserWindow, docState)
    }
  })
}

const importUML = (browserWindow: BrowserWindow, path_: string) => {
  fs.readFile(path_, (error: NodeJS.ErrnoException, buffer: Buffer) => {
    if (error != null) {
      console.log('file open error')
      return
    }

    if (buffer != null) {
      const uml = buffer.toString('utf8')
      const state = convertPlantUMLToState(uml)
      browserWindow.webContents.send('request', 'load', state)

      const docState = getDocState(browserWindow)
      docState.editDirty = true
      docState.filePath = null
      docState.rootText = null
      updateWindowTitle(browserWindow, docState)
    }
  })
}

const isReusableEmptyDocumentWindow = (win: BrowserWindow): boolean => {
  const docState = getDocState(win)
  return docState.filePath == null && !docState.editDirty
}

const findReusableEmptyDocumentWindow = (): BrowserWindow | null => {
  const focused = BrowserWindow.getFocusedWindow()
  if (focused != null && isDocumentWindow(focused) && isReusableEmptyDocumentWindow(focused)) {
    return focused
  }

  // 設定ウィンドウなどが前面でも、空のドキュメントが1つだけならそれを再利用する
  const docs = getDocumentWindows()
  if (docs.length === 1 && isReusableEmptyDocumentWindow(docs[0])) {
    return docs[0]
  }

  return null
}

const openDocumentInNewWindow = (path_: string): void => {
  const existing = findDocumentWindowByPath(path_)
  if (existing != null) {
    focusDocumentWindow(existing)
    return
  }

  const reusable = findReusableEmptyDocumentWindow()
  if (reusable != null) {
    const loadIntoReusable = () => {
      load(reusable, path_)
      focusDocumentWindow(reusable)
    }

    if (reusable.webContents.isLoadingMainFrame()) {
      reusable.webContents.once('did-finish-load', loadIntoReusable)
    } else {
      loadIntoReusable()
    }
    return
  }

  createDocumentWindow(path_)
}

const requestQuit = (): void => {
  const windows = [...getDocumentWindows()]
  let index = 0

  const processNext = () => {
    if (index >= windows.length) {
      app.quit()
      return
    }

    const win = windows[index]
    const docState = getDocState(win)

    if (!docState.editDirty) {
      index++
      processNext()
      return
    }

    const ret = showSaveConfirmDialog()
    if (ret == CONFIRM_ANSWER_SAVE) {
      save(win, () => {
        index++
        processNext()
      })
    } else if (ret == CONFIRM_ANSWER_DELETE) {
      docState.editDirty = false
      index++
      processNext()
    }
  }

  processNext()
}

const createDocumentWindow = (initialFilePath?: string): BrowserWindow => {
  const mainWindow = new BrowserWindow({
    width: 1000,
    height: 800,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
    }
  })

  documentStates.set(mainWindow.id, createInitialDocState())

  mainWindow.on('closed', () => {
    const docState = documentStates.get(mainWindow.id)
    if (docState?.completionAbortController != null) {
      docState.completionAbortController.abort()
    }
    documentStates.delete(mainWindow.id)
  })

  mainWindow.on('close', (event: Event) => {
    const docState = getDocState(mainWindow)
    if (docState.editDirty) {
      const closeWindow = () => {
        docState.editDirty = false
        mainWindow.destroy()
      }

      const ret = showSaveConfirmDialog()
      if (ret == CONFIRM_ANSWER_SAVE) {
        event.preventDefault()
        save(mainWindow, closeWindow)
      } else if (ret == CONFIRM_ANSWER_DELETE) {
        docState.editDirty = false
      } else {
        event.preventDefault()
      }
    }
  })

  mainWindow.webContents.on('did-finish-load', () => {
    setDarkMode(store.get('darkMode'))

    if (initialFilePath != null) {
      load(mainWindow, initialFilePath)
    } else if (pendingFilePath != null) {
      load(mainWindow, pendingFilePath)
      pendingFilePath = null
    }
  })

  mainWindow.webContents.on('before-input-event', (event: Event, input: Input) => {
    if (input.key === 'Escape') {
      cancelCompletionForWindow(mainWindow)
      event.preventDefault()
    }
  })

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY)
  updateWindowTitle(mainWindow, getDocState(mainWindow))

  return mainWindow
}

const openSettings = () => {
  const settingsWindow = new BrowserWindow({
    width: 640,
    height: 390,
    title: 'Settings',
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: SETTINGS_PRELOAD_WEBPACK_ENTRY
    }
  })

  settingsWindow.loadURL(SETTINGS_WEBPACK_ENTRY)
}

ipc.handle('invoke', async (event: IpcMainEvent, arg: string): Promise<any> => {
  if (arg === 'get-settings') {
    const settings = {
      darkMode: store.get('darkMode'),
      openaiApiKey: store.get('openaiApiKey'),
      completionModel: store.get('completionModel'),
      completionContext: store.get('completionContext')
    }
    return settings
  } else {
    return null
  }
})

app.on('ready', () => {
  createDocumentWindow()
})

app.on('window-all-closed', () => {
  app.quit()
})

app.on('activate', () => {
  if (getDocumentWindows().length === 0) {
    createDocumentWindow()
  }
})

app.on('open-file', (event: Event, path_: string) => {
  event.preventDefault()

  if (!app.isReady()) {
    pendingFilePath = path_
    return
  }

  openDocumentInNewWindow(path_)
})

ipc.on('response', (event: IpcMainEvent, arg: string, obj: any) => {
  if (arg == 'settings-set-dark-mode') {
    const darkMode = obj as boolean
    store.set('darkMode', darkMode)
  } else if (arg == 'settings-set-openai-api-key') {
    const openaiApiKey = obj as string
    store.set('openaiApiKey', openaiApiKey)
  } else if (arg == 'settings-set-completion-model') {
    const completionModel = obj as string
    store.set('completionModel', completionModel)
  } else if (arg == 'settings-set-completion-context') {
    const completionContext = obj as string
    store.set('completionContext', completionContext)
  } else if (arg == 'set-dirty') {
    const win = getDocWindowFromSender(event.sender)
    if (win == null) {
      return
    }
    const docState = getDocState(win)
    docState.editDirty = true
    updateWindowTitle(win, docState)
  } else if (arg == 'set-root-text') {
    const win = getDocWindowFromSender(event.sender)
    if (win == null) {
      return
    }
    getDocState(win).rootText = obj
  } else if (arg == 'response-save') {
    const win = getDocWindowFromSender(event.sender)
    if (win == null) {
      return
    }
    const docState = getDocState(win)
    if (docState.filePath == null) {
      return
    }

    const mapData = {
      version: DATA_VERSION,
      state: obj
    }

    const json = JSON.stringify(mapData, null, '  ')

    fs.writeFile(docState.filePath, json, (error: NodeJS.ErrnoException) => {
      if (error != null) {
        console.log('save error')
      }
    })

    docState.editDirty = false
    onSaveFinished(win, docState)
  } else if (arg == 'response-export') {
    const win = getDocWindowFromSender(event.sender)
    if (win == null) {
      return
    }
    const docState = getDocState(win)
    if (docState.exportFilePath == null) {
      return
    }

    const [state, format] = obj as [SavingNodeState, string]
    const content =
      format == 'uml'
        ? convertStateToPlantUML(state)
        : format == 'json'
          ? convertStateToJSON(state)
          : convertStateToYAML(state)

    fs.writeFile(docState.exportFilePath, content, (error: NodeJS.ErrnoException) => {
      if (error != null) {
        console.log('save error')
      }
    })

    docState.exportFilePath = null
  } else if (arg == 'response-complete') {
    const win = getDocWindowFromSender(event.sender)
    if (win == null) {
      return
    }
    const docState = getDocState(win)
    const state = obj
    const sender = event.sender

    cancelCompletionForWindow(win)
    docState.completionAbortController = new AbortController()

    const openaiApiKey = store.get('openaiApiKey')
    const completionModel = store.get('completionModel')
    const completionContext = store.get('completionContext')

    completeState(
      openaiApiKey,
      completionModel,
      state,
      completionContext,
      docState.completionAbortController
    )
      .then((completedState) => {
        if (completedState != null) {
          sender.send('request', 'completed', completedState)
        } else {
          sender.send('request', 'completed', state)
        }
        docState.completionAbortController = null
      })
      .catch((error) => {
        sender.send('request', 'completed', state)
        console.error(error)
        docState.completionAbortController = null
      })
  } else if (arg == 'response-copy-nodes') {
    sharedCopiedNodes = obj as SavingNodeState[]
  } else if (arg == 'response-clipboard-export') {
    const [state, format] = obj
    const content = format === 'json' ? convertStateToJSON(state) : convertStateToYAML(state)
    clipboard.writeText(content)
  } else if (arg == 'response-text-generate') {
    const win = getDocWindowFromSender(event.sender)
    if (win == null) {
      return
    }
    const docState = getDocState(win)
    const inputText = obj as string
    const sender = event.sender

    cancelCompletionForWindow(win)
    docState.completionAbortController = new AbortController()

    const openaiApiKey = store.get('openaiApiKey')
    const completionModel = store.get('completionModel')

    convertTextToMindMap(openaiApiKey, completionModel, inputText, docState.completionAbortController)
      .then((state) => {
        if (state != null) {
          sender.send('request', 'text-import-complete', { success: true, state })
          docState.editDirty = true
          docState.filePath = null
          docState.rootText = null
          updateWindowTitle(win, docState)
        } else {
          sender.send('request', 'text-import-complete', {
            success: false,
            error: 'Failed to generate MindMap'
          })
        }
        docState.completionAbortController = null
      })
      .catch((error) => {
        sender.send('request', 'text-import-complete', {
          success: false,
          error: error.message || 'An error occurred'
        })
        docState.completionAbortController = null
      })
  } else if (arg == 'cancel-text-generate') {
    const win = getDocWindowFromSender(event.sender)
    if (win == null) {
      return
    }
    cancelCompletionForWindow(win)
  }
})

// ElectronのMenuの設定
const templateMenu: Electron.MenuItemConstructorOptions[] = [
  {
    label: app.name,
    submenu: [
      { role: 'about' },
      { type: 'separator' },
      {
        label: 'Settings',
        accelerator: 'CmdOrCtrl+,',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          openSettings()
        }
      },
      { type: 'separator' },
      { role: 'services' },
      { type: 'separator' },
      { role: 'hide' },
      { role: 'hideOthers' },
      { role: 'unhide' },
      { type: 'separator' },
      {
        label: 'Quit',
        accelerator: 'CmdOrCtrl+Q',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          requestQuit()
        }
      }
    ]
  },
  {
    label: 'File',
    submenu: [
      {
        label: 'New',
        accelerator: 'CmdOrCtrl+N',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          createDocumentWindow()
        }
      },
      {
        label: 'Open',
        accelerator: 'CmdOrCtrl+O',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: Event) => {
          const docWindow = resolveDocumentWindow(browserWindow)

          const requestOpen = () => {
            const options: Electron.OpenDialogSyncOptions = {
              properties: ['openFile'],
              filters: [
                {
                  name: 'narr-map',
                  extensions: ['nm', 'json']
                }
              ]
            }
            const pathes = dialog.showOpenDialogSync(options)
            if (pathes != null && pathes.length > 0) {
              const path_ = pathes[0]
              const existing = findDocumentWindowByPath(path_)
              if (existing != null) {
                focusDocumentWindow(existing)
                return
              }
              load(docWindow, path_)
            }
          }

          const docState = getDocState(docWindow)
          if (docState.editDirty) {
            const ret = showSaveConfirmDialog()
            if (ret == CONFIRM_ANSWER_SAVE) {
              save(docWindow, requestOpen)
            } else if (ret == CONFIRM_ANSWER_DELETE) {
              requestOpen()
            }
          } else {
            requestOpen()
          }
        }
      },
      {
        label: 'Open Recent',
        role: 'recentDocuments',
        submenu: [
          {
            label: 'Clear Recent',
            role: 'clearRecentDocuments'
          }
        ]
      },
      {
        type: 'separator'
      },
      {
        label: 'Save',
        accelerator: 'CmdOrCtrl+S',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          const docWindow = resolveDocumentWindow(browserWindow)
          save(docWindow)
        }
      },
      {
        label: 'Save As',
        accelerator: 'CmdOrCtrl+Shift+S',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          const docWindow = resolveDocumentWindow(browserWindow)
          saveAs(docWindow)
        }
      },
      {
        label: 'Export',
        submenu: [
          {
            label: 'YAML',
            accelerator: 'CmdOrCtrl+Shift+Y',
            click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
              const docWindow = resolveDocumentWindow(browserWindow)
              exportAs(docWindow, 'yaml')
            }
          },
          {
            label: 'JSON',
            accelerator: 'CmdOrCtrl+Shift+J',
            click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
              const docWindow = resolveDocumentWindow(browserWindow)
              exportAs(docWindow, 'json')
            }
          },
          {
            label: 'PlantUML',
            accelerator: 'CmdOrCtrl+Shift+E',
            click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
              const docWindow = resolveDocumentWindow(browserWindow)
              exportAs(docWindow, 'uml')
            }
          }
        ]
      },
      {
        label: 'Import',
        submenu: [
          {
            label: 'PlantUML',
            accelerator: 'CmdOrCtrl+Shift+O',
            click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: Event) => {
              const docWindow = resolveDocumentWindow(browserWindow)

              const requestImport = () => {
                const options: Electron.OpenDialogSyncOptions = {
                  properties: ['openFile'],
                  filters: [
                    { name: 'PlantUML', extensions: ['pu', 'wsd', 'puml', 'plantuml', 'iuml'] }
                  ]
                }
                const pathes = dialog.showOpenDialogSync(options)
                if (pathes != null && pathes.length > 0) {
                  const path_ = pathes[0]
                  importUML(docWindow, path_)
                }
              }

              const docState = getDocState(docWindow)
              if (docState.editDirty) {
                const ret = showSaveConfirmDialog()
                if (ret == CONFIRM_ANSWER_SAVE) {
                  save(docWindow, requestImport)
                } else if (ret == CONFIRM_ANSWER_DELETE) {
                  requestImport()
                }
              } else {
                requestImport()
              }
            }
          },
          {
            label: 'From Text Input',
            accelerator: 'CmdOrCtrl+Shift+T',
            click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: Event) => {
              const docWindow = resolveDocumentWindow(browserWindow)

              const requestTextImport = () => {
                docWindow.webContents.send('request', 'open-text-import-modal')
              }

              const docState = getDocState(docWindow)
              if (docState.editDirty) {
                const ret = showSaveConfirmDialog()
                if (ret == CONFIRM_ANSWER_SAVE) {
                  save(docWindow, requestTextImport)
                } else if (ret == CONFIRM_ANSWER_DELETE) {
                  docState.editDirty = false
                  requestTextImport()
                }
              } else {
                requestTextImport()
              }
            }
          }
        ]
      },
      {
        label: 'Copy to Clipboard',
        submenu: [
          {
            label: 'YAML',
            accelerator: 'CmdOrCtrl+Y',
            click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
              const docWindow = resolveDocumentWindow(browserWindow)
              docWindow.webContents.send('request', 'clipboard-export', 'yaml')
            }
          },
          {
            label: 'JSON',
            accelerator: 'CmdOrCtrl+J',
            click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
              const docWindow = resolveDocumentWindow(browserWindow)
              docWindow.webContents.send('request', 'clipboard-export', 'json')
            }
          }
        ]
      }
    ]
  },
  {
    label: 'Edit',
    submenu: [
      {
        label: 'Undo',
        accelerator: 'CmdOrCtrl+Z',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          const docWindow = resolveDocumentWindow(browserWindow)
          docWindow.webContents.send('request', 'undo')
        }
      },
      {
        label: 'Redo',
        accelerator: 'CmdOrCtrl+Shift+Z',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          const docWindow = resolveDocumentWindow(browserWindow)
          docWindow.webContents.send('request', 'redo')
        }
      },
      {
        type: 'separator'
      },
      {
        label: 'Cut',
        accelerator: 'CmdOrCtrl+X',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          const docWindow = resolveDocumentWindow(browserWindow)
          docWindow.webContents.send('request', 'cut')
        }
      },
      {
        label: 'Copy',
        accelerator: 'CmdOrCtrl+C',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          const docWindow = resolveDocumentWindow(browserWindow)
          docWindow.webContents.send('request', 'copy')
        }
      },
      {
        label: 'Paste',
        accelerator: 'CmdOrCtrl+V',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          const docWindow = resolveDocumentWindow(browserWindow)
          docWindow.webContents.send('request', 'paste', {
            nodes: sharedCopiedNodes,
            text: clipboard.readText()
          })
        }
      },
      {
        type: 'separator'
      },
      {
        label: 'Select All',
        accelerator: 'CmdOrCtrl+A',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          const docWindow = resolveDocumentWindow(browserWindow)
          docWindow.webContents.send('request', 'selectall')
        }
      },
      {
        type: 'separator'
      },
      {
        label: 'Complete With AI',
        accelerator: 'CmdOrCtrl+M',
        click: (menuItem: MenuItem, browserWindow: BrowserWindow, event: KeyboardEvent) => {
          const docWindow = resolveDocumentWindow(browserWindow)
          docWindow.webContents.send('request', 'complete')
        }
      }
    ]
  },
  {
    label: 'View',
    submenu: [
      {
        role: 'reload'
      },
      {
        type: 'separator'
      },
      {
        role: 'resetZoom'
      },
      {
        role: 'zoomIn'
      },
      {
        role: 'zoomOut'
      },
      {
        type: 'separator'
      },
      {
        role: 'togglefullscreen'
      },
      {
        role: 'toggleDevTools'
      }
    ]
  }
]

const menu = Menu.buildFromTemplate(templateMenu)

app.whenReady().then(() => {
  Menu.setApplicationMenu(menu)
})
