name: Create Release Draft

on:
  push:
    branches: [build]

jobs:
  create_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Create release draft
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
